#
# For licensing see accompanying LICENSE file.
# Copyright (C) 2023 Apple Inc. All Rights Reserved.
#
env: quadruped_walk
pebble:
  agent.params.actor_lr: 0.0001
  agent.params.critic_lr: 0.0001
  reward_update: 50
  reward_lr: 3e-4
  gradient_update: 1
  activation: tanh
  num_unsup_steps: 9000
  num_train_steps: 1000000
  num_interact: 30000
contrastive_reed:
  joint_learning: false
  self_future_consistency_pretrain: true
  self_future_consistency_lr: 1e-4
  self_future_consistency_optimizer: "adam"
  self_future_consistency_epochs: 20
  self_future_consistency_batch: 128
  reward_state_embed_dim: 78
  reward_action_embed_dim: 12
  self_future_consistency_projection_size: 78
  activation: tanh
  contrastive_sfc: true # trains the SFC network with a contrastive loss instead of a SimSiam style loss
  temperature: 0.5
distillation_reed:
  joint_learning: false
  self_future_consistency_pretrain: true
  self_future_consistency_lr: 1e-4
  self_future_consistency_optimizer: "adam"
  self_future_consistency_epochs: 20
  self_future_consistency_batch: 128
  reward_state_embed_dim: 78
  reward_action_embed_dim: 12
  self_future_consistency_projection_size: 78
  activation: tanh
  contrastive_sfc: false # trains the SFC network with a SimSiam style loss
  temperature: 0.
