#
# For licensing see accompanying LICENSE file.
# Copyright (C) 2023 Apple Inc. All Rights Reserved.
#
defaults:
    - agent: sac
    
# this needs to be specified manually
experiment: pebble

# the location where the results and models will be written
out_dir:

# the random seed that will be used for running the experiments
seed: 1

# Environment
env: walker_walk

# device used to run experiments
device: cuda

# reward learning
segment_size: 50
activation: tanh
reward_state_embed_dim: 20
reward_action_embed_dim: 10
reward_hidden_embed_dim: 256
reward_num_hidden_layers: 3
reward_lr: 0.0003
reward_optimizer: "adam"
reward_weight_decay: 0
reward_train_batch: 100
reward_update: 50  # the number of training epochs for each preference dataset version
ensemble_size: 3
assess_ensemble_disagreement: true

# added to handle learning the reward on top of image observations
reward_from_image_observations: false
normalized_images: false
grayscale_images: false

# whether to save the image preference dataset
save_image_observations: false
saved_image_height: 200
saved_image_width: 200

# managing and building the preference dataset
max_feedback: 1400
num_interact: 5000
preference_dataset_update_size: ${reward_train_batch}
feed_type: 0
preference_dataset_capacity: ${max_feedback}
preference_dataset_large_update_size: 10
label_margin: 0.0
teacher_beta: -1
teacher_gamma: 1
teacher_eps_mistake: 0
teacher_eps_skip: 0
teacher_eps_equal: 0

# policy training
action_repeat: 1
num_train_steps: 1e6
num_seed_steps: 1000
num_unsup_steps: 5000
reset_update: 100
replay_buffer_capacity: ${num_train_steps}
gradient_update: 1

# determines how many states are compared during unsupervised exploration
topK: 5

# evaluation config
eval_frequency: 10000
num_eval_episodes: 10

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: false

# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./exp/${env}/H${diag_gaussian_actor.params.hidden_dim}_L${diag_gaussian_actor.params.hidden_depth}_lr${agent.params.actor_lr}/teacher_b${teacher_beta}_g${teacher_gamma}_m${teacher_eps_mistake}_s${teacher_eps_skip}_e${teacher_eps_equal}/label_smooth_${label_margin}/schedule_${reward_schedule}/${experiment}_init${num_seed_steps}_unsup${num_unsup_steps}_inter${num_interact}_maxfeed${max_feedback}_seg${segment}_act${activation}_Rlr${reward_lr}_Rbatch${reward_batch}_Rupdate${reward_update}_en${ensemble_size}_sample${feed_type}_large_batch${large_batch}_seed${seed}
